### YamlMime:ManagedReference
items:
- uid: TGBot.Application
  commentId: N:TGBot.Application
  id: TGBot.Application
  children:
  - TGBot.Application.AppHost
  - TGBot.Application.BotService
  - TGBot.Application.CommandHandler
  - TGBot.Application.DownloadCoordinator
  - TGBot.Application.MessageRouter
  langs:
  - csharp
  - vb
  name: TGBot.Application
  nameWithType: TGBot.Application
  fullName: TGBot.Application
  type: Namespace
  assemblies:
  - tgdl-bot
references:
- uid: TGBot.Application.AppHost
  commentId: T:TGBot.Application.AppHost
  href: TGBot.Application.AppHost.html
  name: AppHost
  nameWithType: AppHost
  fullName: TGBot.Application.AppHost
- uid: TGBot.Application.BotService
  commentId: T:TGBot.Application.BotService
  href: TGBot.Application.BotService.html
  name: BotService
  nameWithType: BotService
  fullName: TGBot.Application.BotService
- uid: TGBot.Application.CommandHandler
  commentId: T:TGBot.Application.CommandHandler
  parent: TGBot.Application
  href: TGBot.Application.CommandHandler.html
  name: CommandHandler
  nameWithType: CommandHandler
  fullName: TGBot.Application.CommandHandler
- uid: TGBot.Application.DownloadCoordinator
  commentId: T:TGBot.Application.DownloadCoordinator
  parent: TGBot.Application
  href: TGBot.Application.DownloadCoordinator.html
  name: DownloadCoordinator
  nameWithType: DownloadCoordinator
  fullName: TGBot.Application.DownloadCoordinator
- uid: TGBot.Application.MessageRouter
  commentId: T:TGBot.Application.MessageRouter
  parent: TGBot.Application
  href: TGBot.Application.MessageRouter.html
  name: MessageRouter
  nameWithType: MessageRouter
  fullName: TGBot.Application.MessageRouter
- uid: TGBot.Application
  commentId: N:TGBot.Application
  href: TGBot.html
  name: TGBot.Application
  nameWithType: TGBot.Application
  fullName: TGBot.Application
  spec.csharp:
  - uid: TGBot
    name: TGBot
    href: TGBot.html
  - name: .
  - uid: TGBot.Application
    name: Application
    href: TGBot.Application.html
  spec.vb:
  - uid: TGBot
    name: TGBot
    href: TGBot.html
  - name: .
  - uid: TGBot.Application
    name: Application
    href: TGBot.Application.html
